/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#20201f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c6cf',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'outline': '#8e9198',
        'outline-variant': '#43474e',
        'surface-tint': '#afc8f0',
        'primary': '#afc8f0',
        'on-primary': '#163152',
        'primary-container': '#001f3f',
        'on-primary-container': '#6f88ad',
        'inverse-primary': '#476083',
        'secondary': '#e9c176',
        'on-secondary': '#412d00',
        'secondary-container': '#604403',
        'on-secondary-container': '#dab36a',
        'tertiary': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#1d1f1f',
        'on-tertiary-container': '#858687',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d4e3ff',
        'primary-fixed-dim': '#afc8f0',
        'on-primary-fixed': '#001c3a',
        'on-primary-fixed-variant': '#2f486a',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353535'
      },
      spacing: {
        'container-max': '1280px',
        'gutter': '24px',
        'margin-x': '32px',
        'section-padding': '120px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px'
      },
      maxWidth: {
        'container-max': '1280px',
      }
    },
  },
  plugins: [],
}
